app.py
from flask import Flask
import os
from src.routes import bp as routes_bp
from src.functions import db_cli
from src.filters import *

app = Flask(__name__, template_folder='templates', static_folder='static')

app.secret_key = os.getenv("FLASK_SECRET_KEY") or "braingainssecretkey"
app.register_blueprint(routes_bp)
app.cli.add_command(db_cli)

with app.app_context():
    app.jinja_env.filters['days_ago']       = jinja_days_ago
    app.jinja_env.filters['question_boxes'] = jinja_question_boxes
    app.jinja_env.filters['answer_boxes']   = jinja_answer_boxes

if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=5000)

src/routes.py
from flask import Blueprint, redirect, url_for, render_template, request, flash
import markdown2
import logging
from .functions import *

bp = Blueprint('app', __name__)


@bp.route("/", methods=("GET", "POST"))
def index():
    topics_by_section = get_uncompleted_topics_by_section()
    counts = get_total_uncompleted_questions_per_topic()
    if topics_by_section is None or counts is None:
        return render_template("init_db.html")
    return render_template("index.html", topics_by_section=topics_by_section, counts=counts)


@bp.route("/init_db", methods=("GET", "POST"))
def init_db():
    if request.method == "POST":
        reinitialize_db()
        return redirect(url_for("app.index"))
    return render_template("init_db.html")


@bp.route("/reset_db", methods=(["POST"]))
def reset_db():
    if request.method == "POST":
        reinitialize_db()
        return redirect(url_for("app.index"))
    return render_template("init_db.html")


@bp.route("/about")
def about():
    return render_template("about.html")


@bp.route("/question/<section>/<topic>", methods=("GET", "POST"))
@bp.route("/question/<section>/<topic>/<id>", methods=("GET", "POST"))
def question(section: str = None, topic: str = None, id=None):
    if id:
        query = get_question(section, topic, id)
    else:
        query = get_question(section, topic)
        if query:
            return redirect(url_for('app.question', section=section, topic=topic, id=query['id']))

    if query:
        query_dict = dict(query)
        lowerCaseQuery = {k.lower(): v for k, v in query_dict.items()}
        markdownQuery = lowerCaseQuery
        markdownQuery['question'] = markdown2.markdown(
            markdownQuery['question'], extras=["fenced-code-blocks"])
        markdownQuery['answer'] = markdown2.markdown(
            markdownQuery['answer'], extras=["fenced-code-blocks"])
        return render_template("question.html", query=markdownQuery)
    else:
        flash('Good Job, you don\'t have any more questions to answer for today\'s quiz. You should check back daily, as a quiz listed here is not yet mastered <i class="bi bi-mortarboard-fill text-info m1"></i>', 'success')
        return redirect(url_for("app.index"))


@bp.route("/answer/<section>/<topic>/<id>", methods=("GET", "POST"))
def answer(section, topic, id):
    score = int(request.form["score"])
    update_box(id, score)
    time = datetime.now()
    update_lastreview(id, time)
    query = get_question(section=section, topic=topic, min_id=id)
    if query is None:
        return redirect(url_for("app.index"))

    url = "/question/" + query["section"] + "/" + \
        query["topic"] + "/" + str(query["id"])
    return redirect(url)


@bp.route("/create", methods=("GET", "POST"))
def create():
    if request.method == "POST":
        existing_section_and_topic = request.form.get(
            "existingsectionandtopic")
        new_section = request.form.get("newsection")
        new_topic = request.form.get("newtopic")
        question = request.form["question"]
        answer = request.form["answer"]

        if new_section:
            section = new_section
        else:
            section = existing_section_and_topic.split(" > ")[0]

        if new_topic:
            topic = new_topic
        else:
            topic = existing_section_and_topic.split(" > ")[1]

        if create_new_question(topic, question, answer, section):
            return redirect(url_for("app.create"))
        else:
            return "Error creating question"
    elif request.method == "GET":
        topics_by_section = get_topics_by_section()
        counts = get_total_questions_per_topic()
        if topics_by_section is None or counts is None:
            return render_template("init_db.html")
        latest_question = select()[-1]
        latest_topic = latest_question['TOPIC']
        latest_section = latest_question['SECTION']
        return render_template("create.html", topics_by_section=topics_by_section, counts=counts, latest_topic=latest_topic, latest_section=latest_section)


@bp.route("/list", methods=("GET", "POST"))
def list():
    if request.method == "POST":
        query = select(request.form.get("topic"))
    else:
        query = select()

    topics_by_section = get_topics_by_section()
    if query is None or topics_by_section is None:
        return render_template("init_db.html")

    mastered_topics = {}
    for section, topics in topics_by_section.items():
        for topic_info in topics:
            topic = topic_info['topic']
            mastered_topics[(section, topic)] = are_all_questions_mastered(
                section, topic)

    return render_template("list.html", query=query, topics_by_section=topics_by_section, mastered_topics=mastered_topics)


@bp.route("/edit/<int:id>", methods=("GET", "POST"))
def edit(id):
    if request.method == "POST":
        existing      = request.form.get("existingsectionandtopic")
        new_section   = request.form.get("newsection")
        new_topic     = request.form.get("newtopic")
        question      = request.form["question"]
        answer        = request.form["answer"]
        box           = request.form["box"]
        reset_date    = request.form.get("resetDate")
        section       = new_section if new_section else existing.split(" > ")[0]
        topic         = new_topic if new_topic else existing.split(" > ")[1]

        if reset_date:
            lastreview = None
        else:
            lastreview = get_question_by_id(id)['LASTREVIEW']

        update_question(id, topic, question, answer, box, section, lastreview)
        return redirect(url_for("app.list"))
    else:
        question = get_question_by_id(id)

        if question is None:
            logging.error(
                f"Question with id {id} not found when trying to edit.")
            return redirect(url_for("app.list"))
        topics_by_section = get_topics_by_section()
        counts = get_total_questions_per_topic()
        return render_template("edit.html", question=question, topics_by_section=topics_by_section, counts=counts)


@bp.route("/editTopic/<path:topic>", methods=("GET", "POST"))
def editTopic(topic):
    if request.method == "POST":
        newSection = request.form["section"]
        newTopic = request.form["topic"]
        edit_topic(topic, newTopic)
        edit_section(newTopic, newSection)
        return redirect(url_for("app.list"))
    if request.method == "GET":
        section = get_section_by_topic(topic)
        if section is None:
            logging.error(
                f"Section {section} not found when trying get edit topic {topic}.")
            return redirect(url_for("app.list"))
        return render_template("editTopic.html", topic=topic, section=section)


@bp.route("/delete/<int:id>", methods=("POST",))
def delete(id):
    question = get_question_by_id(id)
    if question is None:
        logging.error(f"Question {id} not found when trying to delete.")
    else:
        delete_question(id)
    return redirect(url_for("app.list"))


@bp.route("/deleteTopic/<topic>", methods=("POST",))
def deleteTopic(topic):
    deleteATopic(topic)
    return redirect(url_for("app.list"))


@bp.route("/reset/<section>/<topic>", methods=["POST"])
def reset(section, topic):
    if reset_questions(section, topic):
        logging.debug(
            f"All questions in section '{section}' and topic '{topic}' have been reset to box 1.", "success")
    else:
        logging.error(
            f"Failed to reset questions in section '{section}' and topic '{topic}'.", "error")
    return redirect(url_for("app.list"))

templates/about.html
{% extends "layout.html" %} {% block title %} About {% endblock %} {% block main %}

<p class="text-start">
  Brain Gains is a flashcard app that uses the basic methods of the
  <a href="https://en.wikipedia.org/wiki/Leitner_system">Leitner System</a>. You can use it to write flash cards in
  question and answer form. Then quiz yourself on the topic. By practicing recall with spaced repetition, we ensure we
  retain the information better.
</p>

<p class="text-start">
  The Leitner system is a method to schedule how often you might test recalling the answer to a flash card question.
</p>
<p><img src="/static/2560px-Leitner_system_alternative.svg.png" alt="Leitner Learning System" width="500" height="300" style="background-color: lightgrey;" /></p>

<h2 class="m-3"><strong>BrainGains</strong> helps keep all of this simple and organized for you.</h2><br />

<h3 class="text-start mt-3 mb-3"><strong>Instructions</strong></h3><br />
<p class="text-start indent">
    <strong>1. Take a Course</strong><br />
    <strong>2. Write Flashcards as Notes</strong><br />
    <strong>3. Quiz Daily</strong><br />
    <strong>4. Repeat until you're not offered any questions.</strong><br />
</p>

<h3 class="text-start mt-3 mb-3"><strong>How it Works</strong></h3><br />
<p class="text-start indent">
  <strong>Session 1:</strong><br />
  To start, all questions are in Box 1.<br />
  Quiz on those questions, Correct questions move up one box, incorrect questions go back to Box 1.<br />
  You will rate how you did on the question, choosing correct or incorrect.
</p>

<p class="text-start indent">
  <strong>Session 2:</strong><br />
  The next day you would quiz, using Box 1 and Box 2 questions.<br />
  Correct questions move up one box, incorrect questions go back to Box 1.
</p>

<p class="text-start indent">
  <strong>Session 3:</strong><br />
  Day 3, quiz Box 1, Box 2, and Box 3 together.<br />
  Correct questions move up one box, incorrect questions go back to Box 1.
</p>

<p class="text-start indent">Leitner suggests the following spacing:</p>
<ul class="text-start">
  <li>Box 1: Review daily.</li>
  <li>Box 2: Review every 2 days.</li>
  <li>Box 3: Review every 4 days.</li>
  <li>Box 4: Review every 8 days.</li>
  <li>Box 5: Review every 16 days.</li>
</ul>

<p><img src="/static/Leitner_system_animation.gif" alt="Animated gif of Leitner Learning System" class="darkmode-image-filter" /></p>

<p>This process repeats over time until you've graduated the question, it moves into Box 6, and you will no longer be asked it.<br/>

{% endblock %}

templates/create.html
{% extends "layout.html" %}

{% block title %}
Create
{% endblock %}

{% block main %}
<form class="form-inline" action="/create" method="POST">
    <div class="row">
        <div class="col text-center">
            <div class="form-group mx-sm-3 mb-2 text-center">
                {% if topics_by_section %}
                <label for="existingsectionandtopic" class="sr-only mb-1">Existing Section > Existing Topic > Question Count</label>
                <select class="form-control" id="existingsectionandtopic" name="existingsectionandtopic">
                    <option disabled>Choose</option>
                    {% for section, topics in topics_by_section.items() %}
                        {% for topic_info in topics %}
                            {% set topic = topic_info.topic %}
                            <option value="{{ section }} > {{ topic }}"{% if section == latest_section and topic == latest_topic %}selected{% endif %}>{{ section }} > {{ topic }} > {{ counts[topic] }} Questions</option>
                        {% endfor %}
                    {% endfor %}
                </select>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="text-align-center">
            <h4>OR</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <div class="form-group mx-sm-3 mb-2 pt-3">
                <label for="newsection" class="sr-only mb-1">New Section</label>
                <input type="text" class="form-control" id="newsection" name="newsection" placeholder="New Section">
            </div>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <div class="form-group mx-sm-3 mb-2 pt-3">
                <label for="newtopic" class="sr-only mb-1">New Topic</label>
                <input type="text" class="form-control" id="newtopic" name="newtopic" placeholder="New Topic">
            </div>
        </div>
    </div>
    <div class="form-group text-start pt-4 pb-4 mt-4">
        <label for="toggle-tab">Shift + Tab Spacing</label>
        <button id="toggle-tab" class="btn btn-outline-secondary" type="button">
            <i id="toggle-icon" class="bi bi-toggle-on"></i>
        </button>
    </div>
    <div class="form-group">
        <label for="question">Question</label>
        <textarea class="form-control" id="question" name="question" rows="14" autofocus></textarea>
    </div>
    <div class="form-group">
        <label for="answer">Answer</label>
        <textarea class="form-control" id="answer" name="answer" rows="14"></textarea>
    </div>
    <div class="form-group pt-4">
        <div class="row">
            <div class="col text-center">
                <button type="submit" class="btn btn-primary mb-2" value="Submit">SUBMIT</button>
            </div>
        </div>
        <div class="row">
            <div class="col-auto text-start mt-4">
                <div class="card w-auto">
                    <h5 class="card-title m-2">docs</h5>
                    <p><a class="m-2" href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown Docs</a></p>
                    <p><a class="m-2" href="https://www.markdownguide.org/extended-syntax/#fenced-code-blocks" target="_blank">Fenced Code Blocks</a></p>
                </div>
            </div>
        </div>
    </div>
</form>

<script src="/static/markdownToggle.js"></script>
{% endblock %}

templates/edit.html
{% extends "layout.html" %}

{% block title %}
Edit Card
{% endblock %}

{% block main %}
<!-- Main form for update fields -->
<form id="update-form" action="/edit/{{ question.id }}" method="POST">
  <div class="row">
    <div class="col text-center">
      <div class="form-group mx-sm-3 mb-2">
        {% if topics_by_section %}
        <label for="existingsectionandtopic" class="mb-1">Existing Section > Existing Topic > Question Count</label>
        <select class="form-control text-center" id="existingsectionandtopic" name="existingsectionandtopic">
          <option disabled>Choose</option>
          {% for section, topics in topics_by_section.items() %}
            {% for topic_info in topics %}
              {% set topic = topic_info.topic %}
              <option value="{{ section }} > {{ topic }}"{% if section == question.section and topic == question.topic %} selected{% endif %}>{{ section }} > {{ topic }} > {{ counts[topic] }} Questions</option>
            {% endfor %}
          {% endfor %}
        </select>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-md-5"></div>
    <div class="col-md-2 text-center">
      <h4>OR</h4>
    </div>
    <div class="col-md-5"></div>
  </div>
  <div class="row mt-2">
    <div class="col-md-5 text-center">
      <div class="form-group mx-sm-3 mb-2">
        <label for="newsection" class="mb-1">New Section</label>
        <input type="text" class="form-control" id="newsection" name="newsection" placeholder="New Section">
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-5 text-center">
      <div class="form-group mx-sm-3 mb-2">
        <label for="newtopic" class="mb-1">New Topic</label>
        <input type="text" class="form-control" id="newtopic" name="newtopic" placeholder="New Topic">
      </div>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-md-5 text-center">
      <div class="form-group mx-sm-3 mb-2">
        <label for="boxSelector">Change Box</label>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-5 text-center">
      <div class="form-group mx-sm-3 mb-2">
        <label for="resetDate">Reset Last Reviewed > ( {{ question.lastreview|days_ago }} )</label>
      </div>            
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 text-center">
      <div class="form-group mx-sm-3 mb-2">
        <div class="row">
          <div class="col">
            <div>
              {{ question.box|question_boxes|safe }}
            </div>
          </div>
          <div class="col">
            <select id="boxSelector" class="form-select text-center" aria-label="Box Select" name="box">
              <option selected>{{ question.box }}</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-5">
      <div class="form-group d-flex justify-content-center pt-2">
        <div class="form-check-reverse">
          <input class="form-check-input" type="checkbox" id="resetDate" name="resetDate">
        </div>
      </div>
    </div>
  </div>
  <div class="row pt-4">
    <div class="col">
      <div class="form-group text-start pt-4">
        <label for="toggle-tab">Shift + Tab Spacing</label>
        <button id="toggle-tab" class="btn btn-outline-success" type="button">
          <i id="toggle-icon" class="bi bi-toggle-on"></i>
        </button>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-5"></div>
  </div>
  <div class="form-group">
    <label for="question">Question</label>
    <textarea class="form-control" id="question" name="question" rows="14" autofocus>{{ question.question }}</textarea>
  </div>
  <div class="form-group">
    <label for="answer">Answer</label>
    <textarea class="form-control" id="answer" name="answer" rows="14">{{ question.answer }}</textarea>
  </div>
</form>

<div class="row pt-4">
  <div class="col-md-4">
    <div class="card">
      <h5 class="card-title m-2">docs</h5>
      <p><a class="m-2" href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown Docs</a></p>
      <p><a class="m-2" href="https://www.markdownguide.org/extended-syntax/#fenced-code-blocks" target="_blank">Fenced Code Blocks</a></p>
    </div>
  </div>
  <div class="col-md-4 d-flex justify-content-center align-items-center">
    <button form="update-form" type="submit" class="btn btn-primary">Update Question {{ question.id }}</button>
  </div>
  <div class="col-md-4 d-flex justify-content-end align-items-center">
    <form action="/delete/{{ question.id }}" method="POST">
      <button type="submit" class="btn btn-danger">Delete Question {{ question.id }}</button>
    </form>
  </div>
</div>

<script src="/static/markdownToggle.js"></script>
{% endblock %}

templates/editTopic.html
{% extends "layout.html" %} {% block title %} Edit Topic {% endblock %} {% block main %} 

<form action="/editTopic/{{ topic }}" method="POST">
  <div class="form-row mx-auto" style="width: 500px">
    <div class="form-group col-md-12">
      <label for="section">Section</label>
      <input type="text" class="form-control" id="section" name="section" value="{{ section }}" />
      <label for="topic">Topic</label>
      <input type="text" class="form-control" id="topic" name="topic" value="{{ topic }}" />
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Update</button>
</form>

<br />
<br />

<form action="/deleteTopic/{{ topic }}" method="POST" color="red">
  <button type="submit" class="btn btn-danger" value="delete">Delete</button>
</form>
{% endblock %}

templates/index.html
{% extends "layout.html" %} {% block title %} Index {% endblock %} {% block main %}
<div class="col">
  <div class="row">
    <div class="col-md-6">
      <div class="card text-start mb-2">
        <h2 class="m-2">Instructions</h2>
        <h4 class="m-2">
          1. Take a Course<br />
          2. Write Flashcards<br />
          3. Quiz Daily<br />
          4. Repeat until no questions are offered<br />
          5. Mastered Quizzes are no longer listed <i class="bi bi-mortarboard-fill text-info"></i><br />
        </h4>
      </div>
      <div class="card">
        <img
          class="m-3"
          src="/static/Awakening.jpeg"
          title="Awakening by Stephanie Dryby https://www.instagram.com/stephaniedyrby/" />
      </div>
    </div>
    <div class="d-grid col text-start">
      <div class="card cardlist">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in
        messages %}
        <div class="alert alert-{{ category }}" role="alert">{{ message|safe }}</div>
        {% endfor %} {% endif %} {% endwith %} {% if topics_by_section %}
        <h2 class="m-2">Quiz Topics!</h2>
        {% for section, topics in topics_by_section.items() %}
        <div class="row m-2">
          <div class="col-lg-12">
            <h3 class="section-header">{{ section }}</h3>
            <div class="row">
              {% for topic_info in topics %} {% set topic = topic_info.topic %}
              <div class="col-md-8">
                <a href="/question/{{ section }}/{{ topic }}" class="quiz-button btn btn-outline-light btn-block topic-header">{{ topic }}</a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endfor %} {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/init_db.html
{% extends "layout.html" %}

{% block title %} Initialize Database {% endblock %}

{% block main %}
<div class="container mt-5">
    <h1>Database Initialization</h1>
    <p>The database file <code>flashcards.db</code> was not found. Would you like to initialize the database?</p>
    <form action="{{ url_for('app.init_db') }}" method="POST">
        <button type="submit" class="btn btn-primary">Initialize Database</button>
    </form>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>

<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link rel="icon" href="/static/2958469-512-Luis-Prado-Atlas-Icon.png" type="image/png" />

    <link
      crossorigin="anonymous"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      rel="stylesheet" />
    <script
      crossorigin="anonymous"
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="/static/styles.css" rel="stylesheet" />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css"
      rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", (event) => {
        document.querySelectorAll("pre code").forEach((block) => {
          hljs.highlightElement(block);
        });
      });
    </script>

    <title>BrainGains: {% block title %}{% endblock %}</title>
  </head>

  <body>
    <nav class="bg-dark border fixed-top navbar navbar-expand-md navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="/static/2958469-512-Luis-Prado-Atlas-Icon.png"
            alt="BrainGains Atlas Navbar Icon"
            class="nav-icon"
            title="'Atlas Icon 2958469' by Luis Prado from Noun Project" />
          <span>BrainGains</span>
        </a>
        <button
          aria-controls="navbar"
          aria-expanded="false"
          aria-label="Toggle navigation"
          class="navbar-toggler"
          data-bs-target="#navbar"
          data-bs-toggle="collapse"
          type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav ms-auto m-2">
            <li class="nav-item"><a class="nav-link" href="/create">Create</a></li>
            <li class="nav-item"><a class="nav-link" href="/list">List Cards</a></li>
            <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
            <li class="nav-item">
              <button id="theme-toggle" class="btn btn-outline-light ms-2">
                <i class="bi bi-moon"></i>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container text-center overflow-auto pt-5"><div class="pt-5">{% block main %}{% endblock %}</div></main>

    <footer class="mb-1 small text-center text-muted">
      Site by <a href="https://www.linkedin.com/in/cody-cardinal-896b661b/">Cody Cardinal</a>
    </footer>
  </body>

  <script src="/static/colorToggle.js"></script>
</html>

templates/list.html
{% extends "layout.html" %}
{% block title %} List {% endblock %}
{% block main %}

<div class="row">
  <div class="col-lg-12">
    <div class="text-start"><h2>Mastered Quizzes = <i class="bi bi-mortarboard-fill text-info m1"></i></h2></div>
    {% for section, topics in topics_by_section.items() %}
    <h3>{{ section }}</h3>
    {% for topic_info in topics %}
    {% set topic = topic_info.topic %}
    {% set count = topic_info.count %}
    
    <div class="accordion" {% set safe_topic = topic|replace(" ", "_")|replace("(", "")|replace(")", "")|replace(",", "")|replace("/", "")|replace("\\", "")|replace("&", "and") %} id="accordionFlush_topic_{{ section|replace(' ', '_') }}_{{ safe_topic }}">
      <div class="accordion-item">
        <div class="accordion-header">
          <button
            class="accordion-button collapsed mb-1"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#topic_{{ section|replace(' ', '_') }}_{{ safe_topic }}"
            aria-expanded="false"
            aria-controls="topic_{{ section|replace(' ', '_') }}_{{ safe_topic }}">
            <h2>
              {{ topic }}
              {% if mastered_topics[(section, topic)] %}
                <i class="bi bi-mortarboard-fill text-info m1"></i>
              {% endif %}
            </h2>
          </button>
        </div>
        <div id="topic_{{ section|replace(' ', '_') }}_{{ safe_topic }}" class="accordion-collapse collapse" data-bs-parent="#accordionFlush_topic_{{ section|replace(' ', '_') }}_{{ safe_topic }}">
          <div class="container ms-0">
            <div class="row">
              <h4 class="col-6 text-start">{{ count }} Questions</h4>
              <div class="col-6 text-end">
                <a class="btn btn-success" href="{{ url_for('app.question', section=section, topic=topic) }}">Take the Quiz</a>
                <a class="btn btn-primary" href="{{ url_for('app.editTopic', topic=topic) }}">Edit Topic</a>
                <form action="{{ url_for('app.reset', section=section, topic=topic) }}" method="POST" class="d-inline">
                  <button type="submit" class="btn btn-warning">Move All Questions to Box 1</button>
                </form>
              </div>
            </div>
          </div>
          <div class="accordion-body">
            <table class="table">
              <thead>
                <tr>
                  <th class="text-center">id</th>
                  <th class="text-center">Question</th>
                  <th class="text-start">Answer</th>
                  <th class="text-start">Box</th>
                </tr>
              </thead>
              <tbody>
              {% for question in query if question.topic == topic and question.section == section %}
                <tr>
                  <td class="text-center">
                    <a href="{{ url_for('app.edit', id=question.id) }}">{{ question.id }}</a>
                  </td>
                  <td class="text-start">{{ question.question }}</td>
                  <td class="text-start">{{ question.answer }}</td>
                  <td class="text-center">{{ question.box }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endfor %}
<form action="{{ url_for('app.reset_db') }}" method="POST" onsubmit="return confirm('Are you sure you want to delete and initialize the flashcards.db database? All Questions will be lost.');">
    <div class="mt-5 mb-5">
    <button type="submit" class="btn btn-danger">Delete and Initialize Database</button>
  </form>
</div>
{% endblock %}